[book]
authors = ["Dmitry Stepanov"]
language = "en"
multilingual = false
src = "src"
title = "RG3D Cheat Book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/rg3d-book/rg3d-book.github.io"
git-repository-icon = "fa-github"
